version: 2

before:
  hooks: [make build]
builds: [skip: true]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  extra_files:
    - glob: output/*.{tar.gz,zip}
